### ISSUE TITLE
Проект не работает в JavaScript

### ISSUE THREAD

**Issue by ionin-code** [MandCS/MandCSSync#1]
Не могу скомпилировать в [HTML](https://ok.ru).

Версия Windows: 10.

**Comment by MandCS** [comment]
Здравствуйте.

А на какой версии HTML вы компилируете данный проект?

**Comment by ionin-code** [comment]
HTML 5.

**Comment by MandCS** [comment]
Надо использовать HTML версии neschetnaya-epsilon-cep'.
